In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

# Data Preparation

In [2]:
procedures = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/procedures.csv')
payers = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/payers.csv')
encounters = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/encounters.csv')
organizations = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/organizations.csv')
patients = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/patients.csv')

In [3]:
procedures.shape, payers.shape, encounters.shape, organizations.shape, patients.shape

((47701, 9), (10, 7), (27891, 14), (1, 8), (974, 20))

In [4]:
organizations.head()

,Id,NAME,ADDRESS,CITY,STATE,ZIP,LAT,LON
0,d78e84ec-30aa-3bba-a33a-f29a3a454662,MASSACHUSETTS GENERAL HOSPITAL,55 FRUIT STREET,BOSTON,MA,2114,42.362813,-71.069187

In [5]:
payers.head()

,Id,NAME,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE
0,b3221cfc-24fb-339e-823d-bc4136cbc4ed,Dual Eligible,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,Medicare,7500 Security Blvd,Baltimore,MD,21244.0,1-800-633-4227
2,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,Medicaid,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323
3,d47b3510-2895-3b70-9897-342d681c769d,Humana,500 West Main St,Louisville,KY,40018.0,1-844-330-7799
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,Blue Cross Blue Shield,Michigan Plaza,Chicago,IL,60007.0,1-800-262-2583

In [6]:
patients.head()

,Id,BIRTHDATE,DEATHDATE,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON
0,5605b66b-e92d-c16c-1b83-b8bf7040d51f,1977-03-19,NaN,Mrs.,Nikita578,Erdman779,NaN,Leannon79,M,white,nonhispanic,F,Wakefield Massachusetts US,510 Little Station Unit 69,Quincy,Massachusetts,Norfolk County,2186.0,42.290937,-70.975503
1,6e5ae27c-8038-7988-e2c0-25a103f01bfa,1940-02-19,NaN,Mr.,Zane918,Hodkiewicz467,NaN,NaN,M,white,nonhispanic,M,Brookline Massachusetts US,747 Conn Throughway,Boston,Massachusetts,Suffolk County,2135.0,42.308831,-71.063162
2,8123d076-0886-9007-e956-d5864aa121a7,1958-06-04,NaN,Mr.,Quinn173,Marquardt819,NaN,NaN,M,white,nonhispanic,M,Gardner Massachusetts US,816 Okuneva Extension Apt 91,Quincy,Massachusetts,Norfolk County,2170.0,42.265177,-70.967085
3,770518e4-6133-648e-60c9-071eb2f0e2ce,1928-12-25,2017-09-29,Mr.,Abel832,Smitham825,NaN,NaN,M,white,hispanic,M,Randolph Massachusetts US,127 Cole Way Unit 95,Boston,Massachusetts,Suffolk County,2118.0,42.334304,-71.066801
4,f96addf5-81b9-0aab-7855-d208d3d352c5,1928-12-25,2014-02-23,Mr.,Edwin773,Labadie908,NaN,NaN,M,white,hispanic,M,Stow Massachusetts US,976 Ziemann Gateway,Boston,Massachusetts,Suffolk County,2125.0,42.346771,-71.058813

In [7]:
procedures.head()

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,32c84703-2481-49cd-d571-3899d5820253,265764009,Renal dialysis (procedure),903,NaN,NaN
1,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,c98059da-320a-c0a6-fced-c8815f3e3f39,76601001,Intramuscular injection,2477,NaN,NaN
2,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,703423002,Combined chemotherapy and radiation therapy (p...,11620,363406005.0,Malignant tumor of colon
3,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,17966936-0878-f4db-128b-a43ae10d0878,173160006,Diagnostic fiberoptic bronchoscopy (procedure),9796,162573006.0,Suspected lung cancer (situation)
4,2011-01-05T12:58:36Z,2011-01-05T16:42:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,9de5f0b0-4ba4-ce6f-45fb-b55c202f31a5,265764009,Renal dialysis (procedure),1255,NaN,NaN

In [8]:
encounters.head()

,Id,START,STOP,PATIENT,ORGANIZATION,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185347001,Encounter for problem (procedure),85.55,1018.02,0.00,NaN,NaN
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,outpatient,308335008,Patient encounter procedure,142.58,2619.36,0.00,NaN,NaN
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03T14:32:11Z,2011-01-03T14:47:11Z,73babadf-5b2b-fee7-189e-6f41ff213e01,d78e84ec-30aa-3bba-a33a-f29a3a454662,7caa7254-5050-3b5e-9eae-bd5ea30e809c,outpatient,185349003,Encounter for check up (procedure),85.55,461.59,305.27,NaN,NaN
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03T16:24:45Z,2011-01-03T16:39:45Z,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,d78e84ec-30aa-3bba-a33a-f29a3a454662,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),136.80,1784.24,0.00,NaN,NaN
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03T17:36:53Z,2011-01-03T17:51:53Z,fa006887-d93c-d302-8b89-f3c25f88c0e1,d78e84ec-30aa-3bba-a33a-f29a3a454662,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,ambulatory,390906007,Follow-up encounter,85.55,234.72,0.00,55822004.0,Hyperlipidemia

In [9]:
encounters = encounters.merge(payers, left_on='PAYER', right_on='Id')

In [10]:
encounters = encounters.merge(patients, left_on='PATIENT', right_on='Id',
                              suffixes=('_enc', '_pat'))

In [11]:
encounters.columns

Index(['Id_x', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER',
       'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST',
       'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION',
       'Id_y', 'NAME', 'ADDRESS_enc', 'CITY_enc', 'STATE_HEADQUARTERED',
       'ZIP_enc', 'PHONE', 'Id', 'BIRTHDATE', 'DEATHDATE', 'PREFIX', 'FIRST',
       'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER',
       'BIRTHPLACE', 'ADDRESS_pat', 'CITY_pat', 'STATE', 'COUNTY', 'ZIP_pat',
       'LAT', 'LON'],
      dtype='object')

In [12]:
encounters = encounters[[
       'Id_x', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER',
       'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST',
       'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION',
     #  'Id_y',
       'NAME',
       #'ADDRESS_enc', 'CITY_enc',
       'STATE_HEADQUARTERED',
      # 'ZIP_enc',
       'PHONE',
       #'Id',
       'BIRTHDATE', 'DEATHDATE', 'PREFIX', 'FIRST',
       'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER',
       'BIRTHPLACE', 'ADDRESS_pat', 'CITY_pat', 'STATE', 'COUNTY', 'ZIP_pat',
       'LAT', 'LON',
]]

In [13]:
encounters = encounters.rename(columns={
    'Id_x': 'Id',
    'ENCOUNTERCLASS': 'ENCOUNTER_CLASS',
    'REASONCODE': 'REASON_CODE',
    'REASONDESCRIPTION': 'REASON_DESCRIPTION',
    'ADDRESS_pat': 'ADDRESS',
    'CITY_pat': 'CITY',
    'ZIP_pat': 'ZIP',
    'LAT': 'LATITUDE',
    'LON': 'LONGITUDE',
    'NAME': 'PAYER_NAME'
})

In [14]:
encounters.columns

Index(['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER',
       'ENCOUNTER_CLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST',
       'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASON_CODE',
       'REASON_DESCRIPTION', 'PAYER_NAME', 'STATE_HEADQUARTERED', 'PHONE',
       'BIRTHDATE', 'DEATHDATE', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN',
       'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS',
       'CITY', 'STATE', 'COUNTY', 'ZIP', 'LATITUDE', 'LONGITUDE'],
      dtype='object')

In [15]:
encounters = encounters[[
     #  'Id',
       'START', 'STOP',
       #'PATIENT', 'ORGANIZATION',  'PAYER',
       'ENCOUNTER_CLASS',
    # 'CODE',
     'DESCRIPTION', 'BASE_ENCOUNTER_COST',
       'TOTAL_CLAIM_COST', 'PAYER_COVERAGE',
     #'REASON_CODE',
       'REASON_DESCRIPTION', 'PAYER_NAME',
     # 'STATE_HEADQUARTERED',
       #'PHONE',
       'BIRTHDATE', 'DEATHDATE',
       #'PREFIX',
       'FIRST', 'LAST',
       #'SUFFIX', 'MAIDEN',
       'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE',
      'ADDRESS','CITY', 'STATE', 'COUNTY', 'ZIP', 'LATITUDE', 'LONGITUDE'
]]

In [16]:
encounters['START'] = pd.to_datetime(encounters['START'])
encounters['STOP'] = pd.to_datetime(encounters['STOP'])

encounters['BIRTHDATE'] = pd.to_datetime(encounters['BIRTHDATE'])
encounters['DEATHDATE'] = pd.to_datetime(encounters['DEATHDATE'])

encounters['AGE'] = encounters['START'].dt.year - encounters['BIRTHDATE'].dt.year

encounters['DURATION_IN_MINS'] = (encounters['STOP'] - encounters['START']).dt.total_seconds() / 60

encounters['FIRST'] = encounters['FIRST'].apply(lambda value: ''.join([i for i in value if not i.isdigit()]))
encounters['LAST'] = encounters['LAST'].apply(lambda value: ''.join([i for i in value if not i.isdigit()]))


encounters['PATIENT_NAME'] = encounters['FIRST'] + ' ' + encounters['LAST']

In [17]:
encounters.columns

Index(['START', 'STOP', 'ENCOUNTER_CLASS', 'DESCRIPTION',
       'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE',
       'REASON_DESCRIPTION', 'PAYER_NAME', 'BIRTHDATE', 'DEATHDATE', 'FIRST',
       'LAST', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE',
       'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LATITUDE', 'LONGITUDE',
       'AGE', 'DURATION_IN_MINS', 'PATIENT_NAME'],
      dtype='object')

In [18]:
encounters['MARITAL'].unique()

array(['M', 'S', nan], dtype=object)

In [19]:
encounters = encounters[[
       'START', 'STOP', 'ENCOUNTER_CLASS', 'DESCRIPTION',
       'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE',
       'REASON_DESCRIPTION', 'PAYER_NAME', 'BIRTHDATE', 'DEATHDATE',
       #'FIRST', 'LAST', 'MARITAL',
       'RACE',
       #'ETHNICITY',
       'GENDER', 'BIRTHPLACE', 'AGE',
       'DURATION_IN_MINS', 'PATIENT_NAME',
       'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LATITUDE', 'LONGITUDE'
]]

In [20]:
encounters['PATIENT_NAME'].unique()

array(["Mariano O'Kon", 'Myrtis Lindgren', 'Efrain Dibbert',
       'Dannie Grimes', 'Abraham Ruecker', 'Sharice Johnston',
       'Jonnie Veum', 'Keren Kuvalis', 'Cinda Carroll', 'Rosanne Schumm',
       'Kimberly Collier', 'Arie Hermann', 'Delmar Hoppe', 'Phylis Block',
       'Kayla Stracke', 'Denis Wolff', 'Ramon Harber', 'Hilaria Fay',
       'Devora Walker', 'Celia Carter', 'Robt Gorczany', 'Maddie Monahan',
       'Tyree Hyatt', 'Alfonzo Bogan', 'Napoleon Wyman', 'Richie Reinger',
       'Saul Eichmann', 'Hollie Block', 'Williemae Blick',
       'Domenic Hudson', 'Marta Valladares', 'Gail Glover',
       'Melynda Balistreri', 'Armand Swaniawski', 'Yolanda Solorzano',
       'Kymberly Roob', 'China Klein', 'Marg Hirthe', 'Jen Wilkinson',
       'Tiffany Lubowitz', 'Sherly Hessel', 'Jos√© Rubio',
       'Junior Padberg', 'Neomi Gutmann', 'Chiquita Lang',
       'Jeannette Nitzsche', 'Howard Hodkiewicz', 'Rosamaria Welch',
       'Brandee Kihn', 'Cherryl Leuschke', 'Marianne Nienow',
       'Peg Gulgowski', 'Floria Heaney', 'Scot Kuphal', 'Diego Ferrer',
       'Antwan Abbott', 'Gil Reilly', 'Raven Kerluke', 'Chi Cummerata',
       'Vina Fahey', 'Orpha Schiller', 'Armando Carrasquillo',
       'Treasa Kuhic', 'Corinne Mante', 'Marcos Parker', 'Ester Acevedo',
       'Jenni Emard', 'Joseph Jenkins', 'Guy Bernhard',
       'Beatriz Villase√±or', 'Tonda Stamm', 'Hunter Harber',
       'Coretta Hettinger', 'Candi Hane', 'Kristal DuBuque',
       'Marylyn Morar', 'Bernardo Fl√≥rez', 'Valencia Schuster',
       'Chung Collins', 'Carrol Howell', 'Wilburn Rogahn', 'Linsey Thiel',
       'Marcelene Yundt', 'Stefan Trantow', 'Pearly Schulist',
       'Maryjo Nicolas', 'Sandy Tillman', 'Elanor Flatley',
       'Ana Luisa Salinas', 'Holley McGlynn', 'Columbus Wolf',
       'Williams Harris', "Nichelle O'Reilly", 'Elisa Tejada',
       'Norine Anderson', 'Hanh Walker', 'Emelda Funk', 'Rex Bosco',
       'Rich Legros', 'Nell Conroy', 'Leonardo Kautzer',
       'Melania Hackett', 'Rafaela Ward', 'Lawerence Vandervort',
       'Travis Treutel', 'Buck Paucek', 'Chi Mante', 'Shellie Lind',
       'Treena Williamson', 'Noelia Fay', 'Tristan Beer', 'Grace Wunsch',
       'Isiah Swaniawski', 'Marlen Schmidt', 'Shakira Schultz',
       'Marian Paucek', 'Spring Crooks', "Bruce O'Keefe",
       'Sammie Pfannerstill', 'Mariano Schroeder', 'Garret Spinka',
       'Jonathon Blanda', 'Renay Jacobs', 'Mohamed Hintz',
       'Donovan Quigley', 'Rina Tremblay', 'Carter Welch',
       'Rosario Bueno', 'Richie Stehr', 'Elli Grady',
       'Adriana Montenegro', 'Georgiana Effertz', 'Mickie Champlin',
       'Loise Yost', 'Virginia Mart√≠nez', 'Lenita Jacobs',
       'Mariette Lindgren', 'Florencio Breitenberg', 'Terri Legros',
       'Ricarda Crooks', 'Tomas Hermann', 'Lauri Ward', 'Mack Yost',
       'Wanda Trantow', 'Maryanne Cormier', 'Raylene Schowalter',
       'Jamal Batz', 'Shondra Hartmann', 'Onie Mraz', 'Gina Langworth',
       'Magnolia Stark', 'Leigh Buckridge', 'Paris Littel', 'Lilia Ponce',
       'Zena Cormier', 'Len Ebert', 'Patrina Jacobson', 'Lashawna Walter',
       'Nery Zulauf', 'Ailene Botsford', 'Morton Powlowski',
       'Allen Schumm', 'Ben Stoltenberg', 'Ronald Sporer',
       'Krysten Bergnaum', 'Connie Runte', 'Cindi Torp', 'Hisako Huels',
       'Charlyn Wehner', 'Tresa Jones', 'Georgiann Kertzmann',
       'Angelo Hermiston', 'Eugene Abernathy', 'Ad√°n Feliciano',
       'Deidra Jacobi', 'Jos√© Emilio Santill√°n', 'Tonisha Shields',
       'Emerson Kuhlman', 'Roy Rohan', 'Rivka Schumm',
       'Hilary Stiedemann', 'Kieth Shields', 'Weldon Nolan',
       'Darrick McClure', 'James Oberbrunner', 'Caridad Tafoya',
       'Stephen Marquardt', 'Melynda McClure', 'Jerica Glover',
       'Cristobal Lomeli', 'Duane Wisozk', 'Maida Kreiger',
       'Jacinto Lynch', 'Allen Dicki', 'Lorena Schaefer',
       'Luciano Hessel', 'Tisha Yost', 'Patricia Sevilla',
       'Alexandria Heaney', 'Maia Wolf', 'Oralee Pacocha',
       'Dulcie Tillman', 'Tasia Heidenreich', 'Danuta Witting',
       'Ram√≥n Segovia', 'Abbie Adams', 'Andra Haag', 'Laverne Rath',
       'Trinidad West', 'Yu Keebler', 'Tiny Schaefer', 'Vennie Collins',
       'Anita Moya', "Charisse O'Keefe", 'Lauran Walter',
       'Helene Kilback', 'Raleigh Frami', 'Lorena Wolf',
       'Millicent Grady', 'Dallas Labadie', "Wanetta O'Hara",
       'Jamika Bechtelar', 'Sandy Brekke', 'Luke Hills',
       'Winona VonRueden', 'Domenic Spinka', 'Gregorio Macejkovic',
       'Elijah Ziemann', 'Karrie Reinger', 'Codi Gleichner',
       'Travis Howe', 'Jarrett Rice', 'Keva Cummerata', 'Emerson Kreiger',
       'Lorenzo Prieto', 'Jermaine Brakus', 'Elma Kub',
       'Ignacio Hermiston', 'Ernestina Bahringer', 'Classie Hilll',
       'Chris Fisher', 'Aleen Kreiger', 'Sophia Marvin', 'Denae Lakin',
       'Tayna Keebler', 'Nikita Erdman', 'Ward Nicolas', 'Dudley Doyle',
       'Miguel √Ångel Griego', 'Malka Moen', 'Rachele Nitzsche',
       'Gaye Borer', 'Argentina Corwin', 'Margert Pagac', 'Lise Tillman',
       'Lynda Lang', 'Victorina Nolan', 'Lorette Borer', 'Grover Torp',
       'Ahmed Kreiger', 'Milly Schmeler', 'Min Schuster',
       'Walter Prohaska', 'Simon Grant', 'Merlin Medhurst', 'Jimmy Cole',
       'Elvis Hackett', 'Benito Zavala', 'Cletus Hauck', 'Song Heaney',
       'Christopher Towne', 'Kurtis Bartell', 'Lewis Nolan',
       'Josiah Purdy', 'Fredrick Gutmann', 'Gaston Schneider',
       'Jon McClure', 'Sid Hermann', 'Miguel Manzanares',
       'Jeremy Schowalter', 'Emelia West', 'Chris Corwin', 'An Toy',
       'Wendell Hessel', 'Nelida Nader', 'Lou Rempel', 'Faustino Mraz',
       'Clemente Vergara', 'Eura Emard', 'Anthony Cronin', 'Cory Smitham',
       'Keva Braun', 'Jos√© Emilio Gast√©lum', 'Cynthia Howell',
       'Maxwell Pfeffer', 'Tommie MacGyver', 'Aubrey Bogisich',
       'Joaquin Murphy', 'Sharon Marks', 'Shani Parisian',
       'Edwin Labadie', 'Josette Hermiston', 'Antone Reilly',
       'Suanne Kutch', 'Georgeanna Roberts', 'Armando Barela',
       'Bryant Tillman', 'Estrella Homenick', 'Issac Predovic',
       'Adolph Kshlerin', 'Les Stroman', 'Benito Griego', 'Beryl Roob',
       'Berneice Heaney', 'Quentin Schmidt', 'Nina Goldner',
       'Elana Pouros', 'Karon Gerhold', 'Abel Smitham', 'Kyle Krajcik',
       'Jay Collins', 'Mackenzie Bergnaum', 'Kieth Johns', 'Trent Graham',
       'Shannon Hartmann', 'Vada Wilderman', 'Garfield Block',
       'Bobbye Dare', 'Lucas Zambrano', 'Gus Muller', 'Jimmie Wilkinson',
       'Erwin Dickens', 'Houston Wiza', 'Yolanda Montoya', 'Lynda Gibson',
       'Guy Hammes', 'Arron King', 'Norah Feeney', 'Terresa Nader',
       'Bernardo N√∫√±ez', 'Enrique Alcala', 'Colin Boyer',
       'Isaac Kshlerin', 'Georgann Kuvalis', 'Lilia Barajas',
       'Pauletta Harris', 'Yuette Vandervort', 'Markus Barrows',
       'Jamey Bartell', 'Maragret Lang', 'Esmeralda Heller',
       'Yolanda Escamilla', 'Tyler Reichel', 'Paris Welch', 'Frank Howe',
       'Deeann Harvey', 'Olin Kerluke', 'Melaine Hintz',
       'Elizebeth Gleichner', 'Duane Gleason', 'Tanisha Hauck',
       'Nick Bergnaum', 'Josef Aufderhar', 'Long Rodriguez', 'Rocio Metz',
       'Claire Schamberger', 'Rudy Marvin', 'Chris Mayer',
       'Leonarda Huels', 'Fernando Murray', 'Elmer Denesik',
       'Isabel Campos', 'Del Wyman', 'Maple Runolfsdottir',
       'Mauricio Connelly', 'Deb Kuhn', 'Diane Luettgen', 'Sun Keebler',
       'Mateo Lerma', 'Raelene Collins', 'Edwin Weissnat',
       'Rudolph Heidenreich', 'Vern Schmeler', 'Alejandro Schaden',
       'Alec Little', 'Sunni Olson', 'Ernesto Tapia', 'Henry Wintheiser',
       "Jan O'Hara", 'Reid Denesik', 'Carina Crist', 'Eliza Murazik',
       'Jamal VonRueden', 'Martin Konopelski', 'Judson Smith',
       'Stefani Bergstrom', 'Lyndon Jakubowski', 'Jamar Mills',
       'Javier Ruiz', 'Geri Kuhic', 'Lelia Ferry', 'Graham Swaniawski',
       'Shamika Rice', 'Bud Turner', 'Bradly Eichmann', 'Denver Ratke',
       'Darrick Nader', 'Roscoe Gorczany', 'Connie McGlynn',
       'Hector Franecki', 'Jennie Cummings', 'Gerald Murray',
       'Jos√© Eduardo Viera', 'Marc Buckridge', 'Lucio Gleason',
       'Alison Braun', 'Charlette Bernhard', 'Faustina McDermott',
       'Antoine Bergnaum', 'Rufus Walsh', 'Lenny Conn', 'Tyree Price',
       'Rashad Reilly', 'Katelin Feil', 'Alexia Harris',
       'Shirlee Reynolds', 'Rogelio Gibson', 'Tonda Von', 'Enola Okuneva',
       'Arlen Barrows', "Hayden O'Connell", 'Donn Stoltenberg',
       'Vera Donnelly', 'Sylvester Bradtke', 'Carmine Eichmann',
       'Wilbur Orn', 'Carlota Alc√°ntar', 'Jos√© Mar√≠a Delgadillo',
       'Lavonia Wunsch', 'Hassan Kerluke', 'Jeffie Torphy',
       'Milton Fisher', 'Arica McLaughlin', 'Vincenzo Raynor',
       'Lesley Corwin', 'Jeffrey Beier', 'Brett Pagac', 'My Jakubowski',
       'Roselle Dietrich', 'Coy Kozey', "Maynard O'Reilly",
       'Lynette Kunde', 'Corey Jacobs', 'Janine McKenzie',
       'Celeste Brown', 'Susanne Herman', 'Elwanda Casper',
       'Paulette Dickens', 'Nigel Carroll', 'Clinton Mayer',
       'Domonique Walter', 'Alayna Bergstrom', 'Nan Daniel',
       'Margrett Kuhic', 'Tiesha Hane', 'Trena Ferry', 'Ester Fern√°ndez',
       'Florencio Anderson', 'Armanda Harber', 'Kenneth Luettgen',
       'Judson Ebert', 'Cheryl Rempel', 'Vonnie Weissnat',
       'Maren Breitenberg', 'Micha Doyle', 'Lorelei Witting',
       'Richard Blanda', 'Lurline Turcotte', 'Sherman Schiller',
       'Libby Wuckert', 'Sondra Witting', 'Jessie Schmidt',
       'Charlott Beier', 'Marco Metz', 'Roselyn Predovic', 'Odessa Fay',
       'Juan Gusikowski', 'Phillip Nienow', 'Frankie Oberbrunner',
       'Franklyn Trantow', 'Adrianna Barrows', 'Grady Medhurst',
       'Tawana Shanahan', 'Jimmy Farrell', 'Hassie Runolfsson',
       'Horace Cremin', 'Ida Kozey', 'Fallon Osinski', 'Blanca Batz',
       'Deedra Hahn', 'Sabine Jerde', 'Lolita Hegmann', 'Sung Legros',
       'Ferdinand Goodwin', 'Teodoro Heredia', 'Meghan Bode',
       'Orville Corwin', 'Stephany Streich', 'Neil Anderson',
       'Jenine Mraz', 'Lance Haag', 'Stacee Fadel', 'Pablo Gamez',
       'Demarcus Ankunding', 'Ali Johns', 'Bok King', 'Carey Kulas',
       'Sharolyn Halvorson', 'Rodney Rempel', 'Brandy Pollich',
       'Reinaldo Schamberger', 'Ida Weber', 'Rebeca Abshire',
       'Graham Carter', 'Brooke Romaguera', 'Nicola Dach', 'Dottie Bogan',
       'Grady Erdman', 'Ismael Powlowski', 'Kathern Bernhard',
       'Dominic Mills', 'Keisha Wolf', 'Henry Emmerich',
       'Gabriel Rosenbaum', 'Larae Wolf', 'Cameron Kemmer',
       'Kelley Treutel', 'Ninfa Parker', 'Ambrose Hettinger',
       'Jerald Nader', 'Teddy Cruickshank', 'Teodoro Bechtelar',
       'Lazaro Herman', 'Eleanora Beatty', 'Liza Flatley',
       'Stormy Hirthe', 'Eduardo Streich', 'Debrah Rutherford',
       'Dewey Parisian', 'Erik Swaniawski', 'Lorene Gleichner',
       'Joshua Baumbach', 'Shelly Mertz', 'Stephanie Douglas',
       'Paulene Rolfson', 'Myrtice Murphy', 'Omer Mueller',
       'Marti Feeney', 'Venita Dooley', 'Ike Becker', 'Kristie Stracke',
       'Cornell Fadel', 'Charles Schimmel', 'Rick Kuhic', 'Mateo Becerra',
       'Lauri DuBuque', 'Lincoln Turcotte', 'Shu Leuschke',
       'Cleo Vandervort', 'Clementine Fritsch', 'Shawn Borer',
       'Vince Grady', 'Song Hills', 'Art Lang', 'Antonia Rubio',
       'Franklyn Heidenreich', 'Dorthy Ward', 'Jill Koch', 'Jan Jast',
       'Dustin Cremin', 'Kurt Konopelski', 'Kristofer Larson',
       'Shawn Simonis', 'Chrissy Rempel', 'Klara Hyatt', 'Willy Metz',
       'Deandre Marvin', 'Jaime Nieto', 'Valarie Rowe', 'Devin Murazik',
       'Vernita Murray', 'Danuta Auer', 'Dennis Johnston', 'Myles Kling',
       'Monroe Quigley', 'Cristobal Brown', 'Roman Roberts', 'Kirk Ratke',
       'Jamie Schmidt', 'Winford Klein', 'Lourdes Nava',
       'Walton Champlin', 'Adrian Upton', 'Pedro Jasso', 'Aretha Muller',
       'Carlos Far√≠as', 'Richard Dicki', 'Ramiro Herrera',
       'Mar√≠a Teresa Pedroza', 'Chance Terry', 'Randell Schulist',
       'Sharon Zulauf', 'Tequila Yost', 'Raquel Abeyta',
       'Lakisha Rolfson', 'Nicol√°s Miranda', 'Michal White',
       'Walter Rohan', 'Ludivina Schaden', 'Lulu Carter',
       'Cyrus Powlowski', 'Norma P√°ez', 'Zane Hodkiewicz',
       'Conrad Hirthe', 'Roberto Holgu√≠n', 'Jos√© Luis Varela',
       'Chauncey Jacobi', 'Hoa Schaefer', 'Camille Auer', 'Glory Deckow',
       'Darren Bruen', 'Jody Thompson', 'Delinda Waelchi',
       'Madge Schimmel', 'Manda Heathcote', 'Alexander Jacobi',
       'Quentin Halvorson', 'Sadie Schultz', 'Dessie Yundt', 'Joey Kunze',
       'Edna Hahn', 'Hollis Considine', 'Claudio Sanford',
       'Juana Delr√≠o', 'Britta Yundt', 'Stuart Hermann',
       'Russell Langosh', 'Jaqueline Rath', 'Ira Gleason',
       'Rodrick Goldner', 'Isreal Borer', 'Robbie McClure',
       'Lourdes Torres', 'Lazaro Rau', 'Consuela Torphy',
       'Angelena Gibson', 'Leana Boyer', 'Mohamed Erdman',
       'Caren Quitzon', 'James Emmerich', 'Jude Leannon',
       'Stanton Ritchie', 'Susan Flatley', 'Esta Kutch', 'Jarrett Cole',
       'Bernardo Heaney', 'Rosa Gollum', 'Ayako Ward', 'Rafael Rico',
       'Wyatt Beier', 'Jame Zboncak', 'Mercedes Chavarr√≠a', 'Mario Vela',
       'Preston Murazik', 'Maurice Hermiston', 'Carla Urrutia',
       'Chadwick Adams', 'Rene Hansen', 'Giovanni Hermann', 'Levi Walsh',
       'Roberto Olivo', 'Dorcas Weissnat', 'Beatriz Arriaga',
       'Arturo Cuellar', 'Gayle Dietrich', 'Nigel Feil', 'Daphne Feest',
       'Vannesa Bode', 'Dale McDermott', 'Francisca Mondrag√≥n',
       'Kirk Beatty', 'Ward Boyer', 'Claude Batz', 'Don McClure',
       'Douglass Dooley', 'Jacquetta Towne', 'Michael Leffler',
       'Marivel Little', 'Tinisha Conroy', 'Evan Baumbach',
       'Florencia Hodkiewicz', 'Glennis Ryan', 'Neal Daugherty',
       'Jude Hills', 'Robbie Kuhlman', 'Maria Zulauf',
       'Filiberto Labadie', 'Lesley Kozey', 'Marquis Torp', 'Tuan Boyer',
       'Luigi Satterfield', 'Brant Buckridge', 'Lacresha Lindgren',
       'Loni Conroy', 'Linh Johns', 'Shelby Schroeder', 'Diana Espinal',
       'Rosario Eichmann', 'Rayford Satterfield', 'Lowell Price',
       'Ken Halvorson', 'Blanca Willms', 'Will Bernier', 'Eliana Ferry',
       'Joya Schimmel', 'Tony Wiegand', 'Jos√© Emilio Mar√≠n',
       'Edgardo Okuneva', 'David S√°enz', 'Shad Welch', 'Maire Rempel',
       'Jacobo Leyva', 'Lois Beahan', 'Erinn Mills', 'Tresa Tromp',
       'Porsha Yost', 'Arlen Bernier', 'Sheba Miller', 'Kayleen Lemke',
       'Jonelle Schowalter', 'Charise Kling', 'Salvador Thompson',
       'Terrell Prohaska', 'Roxane Predovic', 'Wilmer Sporer',
       'Morris Kovacek', 'Eric Weimann', 'Daniela Ochoa', 'Dion Kirlin',
       'Arlie Waters', 'Jeri Leannon', 'Bennett Herman', 'Nick Tillman',
       'Beverly Wintheiser', 'Hildegard Bauch', 'Ezequiel Botsford',
       'Olin Davis', 'Romeo Prosacco', 'Antone Prosacco', 'Mee Hand',
       'Weston Aufderhar', 'Ver√≥nica Prieto', 'Damian Terry',
       'Alonzo Kuhlman', 'Gregorio Valle', 'Zackary Macejkovic',
       'Felicita Hansen', 'Jesus Sanford', 'Eilene Walsh', 'Chung Brekke',
       'Travis Hansen', 'Lucina Wiegand', 'Sang Kilback',
       'Magdalena Mora', 'Anibal Veum', 'Jacob MacGyver',
       'Angelia Gusikowski', 'Alysia Ullrich', 'Carina Ebert',
       'Donette Bailey', 'Cathern Beer', 'Leonora Sauer',
       'Crystal Schuppe', 'Anderson Heidenreich', 'Starla Ebert',
       'Joyce Miller', 'Wilmer Blanda', 'Barbara Pizarro', 'Ira Lowe',
       'Gerardo Valenzuela', 'Beryl Olson', 'Francina Luettgen',
       'Marcelle Rath', 'Carey Fahey', 'Randolph Hauck',
       'Sheldon Witting', 'Ramiro de Jes√∫s', 'Cari Kirlin',
       'Sherill Collier', 'Tom√°s Mojica', 'Riley Rutherford',
       'Armando Rold√°n', 'Vilma Hand', 'Trevor Fadel', 'Arianne Harber',
       'Delbert Effertz', 'Delaine Rippin', 'Violeta Frami',
       'Tommie Emmerich', 'Claud Quigley', 'Carroll Weimann',
       'Forrest Lubowitz', 'Demetra Sawayn', 'Dorotha Legros',
       'Noreen Kuphal', 'Francisco Schultz', 'Sonia Toledo',
       'Olivia Vigil', 'Jos√© Luis Ledesma', 'Hollie Daugherty',
       'Ha Jerde', 'Terrence Wilkinson', 'Coy Okuneva', 'Viola Murphy',
       'Ronny Funk', 'Vernon Turcotte', 'Virgilio Krajcik', 'Maren Torp',
       'Donte Emard', 'Reginald McDermott', 'Kathrine Bogisich',
       'Corrin Heaney', 'Rodger Keeling', 'Lazaro Osinski',
       'Domenic Bruen', 'Neville Schroeder', 'Earnest Gorczany',
       'Bradford Ullrich', 'Lynsey Lakin', 'Nell Hansen', 'Jay Wisozk',
       'Elbert Bergstrom', 'Tomika Stamm', "Tempie O'Keefe",
       'Carlo White', 'Ernesto Windler', 'Marc Wiegand', 'Edra Wehner',
       'Jodi Bruen', 'Mira Trantow', 'Antione Gleason', 'Aldo Hoeger',
       'Audry Bogisich', 'Dustin Volkman', 'Basilia Pollich',
       'Adrian Gleason', 'Buster Weber', 'Karl Schuppe', 'Dwight Batz',
       'Tuan Emmerich', 'Margarito Emard', 'Lynne Hammes',
       'Carlota Greenholt', 'Herma Hahn', 'Nathaniel Gaylord',
       'Luigi Turner', 'Beatriz Enr√≠quez', 'Hilton Schowalter',
       'Jc Luettgen', 'Danny Braun', 'Edward Heidenreich',
       'Latoria Bahringer', 'Barry Dickinson', 'Franklyn Kuhlman',
       'Wm Morar', 'Dani Hirthe', 'Julio Pollich', 'Rodney Weissnat',
       'Jolene Kling', 'Javier Bustos', 'Vashti Bins', 'Izetta Farrell',
       'Maryann Runolfsdottir', 'Fritz Jakubowski', 'Alvin Thiel',
       'Shad Lueilwitz', 'Gus Kuhic', 'Fabian Kub', 'Mitch Bartoletti',
       'Eldon Green', 'Edmond Maggio', 'Marlon Becker', 'Gregorio Yundt',
       'Lucas Su√°rez', 'Ronny Johnson', 'Tyron Jast', 'Bernie Kessler',
       'Mar√≠a Elena Alvarez', 'Shella McDermott', 'Filiberto Weimann',
       'Joie Leannon', 'Frank Donnelly', 'Teddy Cronin',
       'Kristofer Wyman', 'Deidra Skiles', 'Merlin Swift',
       'Isaias Buckridge', 'Rudolph Murray', 'Saundra Kris',
       'Stan Zboncak', 'Minna Walter', 'Oswaldo Kerluke',
       'Lakesha Kautzer', 'Rodrigo Saucedo', 'Marlon Boehm',
       'Quinn Marquardt', 'Horacio Dicki', 'Will Hintz', 'Lorenzo Abrego',
       'Tyson Kertzmann', 'Gregory Schowalter', 'Joel Roberts',
       'Margarito Berge', 'Israel King', 'Mollie Christiansen',
       'Jeff Heathcote', 'Carolyn Lebsack', 'Lasonya Jakubowski',
       'Johnny Strosin', 'Edward Douglas', 'Benny Mayert', 'Gale Conroy',
       'Shane Prosacco', 'Vada Jacobs', 'Hellen Keebler', 'Ad√°n Olivera',
       'Cliff McGlynn', 'Roselyn Auer', 'Twana Rath', 'Faviola Purdy',
       'Hobert Will', 'Michale Jacobi', 'Ver√≥nica Chapa', 'Oren Trantow',
       'Keeley Leuschke', 'Diana Dach', 'Willetta Abshire',
       'Alejandrina Heathcote', 'Berta Weissnat', 'Osvaldo Dare',
       'Cleo Von', 'Latonia Lakin', 'Karl Skiles', 'Daren Greenholt',
       "Mitchell O'Kon", 'Dion Veum', 'Daniel Feeney',
       'Santiago Langworth', 'Jeanna Mann', 'Charles Hayes',
       'Echo Carroll', 'Tommy Olson', 'Gabriela Cerda', 'Reed Zulauf',
       'Zetta McGlynn', 'Hugh Price', 'Monte Kihn',
       'Jarred Runolfsdottir', 'Teodora Streich', 'Maxwell Reichert',
       'Maria Waelchi', 'Cristine Kemmer', 'Johana Walter',
       'Larry Cummings'], dtype=object)

In [21]:
encounters.head()

,START,STOP,ENCOUNTER_CLASS,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASON_DESCRIPTION,PAYER_NAME,BIRTHDATE,...,AGE,DURATION_IN_MINS,PATIENT_NAME,ADDRESS,CITY,STATE,COUNTY,ZIP,LATITUDE,LONGITUDE
0,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,ambulatory,Encounter for problem (procedure),85.55,1018.02,0.0,NaN,NO_INSURANCE,1928-08-25,...,83,212.0,Mariano O'Kon,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766
1,2011-01-05 12:58:36+00:00,2011-01-05 16:42:36+00:00,ambulatory,Encounter for problem (procedure),85.55,1370.79,0.0,NaN,NO_INSURANCE,1928-08-25,...,83,224.0,Mariano O'Kon,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766
2,2011-01-08 16:42:36+00:00,2011-01-08 20:15:36+00:00,ambulatory,Encounter for problem (procedure),85.55,1671.32,0.0,NaN,NO_INSURANCE,1928-08-25,...,83,213.0,Mariano O'Kon,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766
3,2011-01-11 20:15:36+00:00,2011-01-11 22:49:36+00:00,ambulatory,Encounter for problem (procedure),85.55,943.24,0.0,NaN,NO_INSURANCE,1928-08-25,...,83,154.0,Mariano O'Kon,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766
4,2011-01-14 22:49:36+00:00,2011-01-15 01:58:36+00:00,ambulatory,Encounter for problem (procedure),85.55,1744.71,0.0,NaN,NO_INSURANCE,1928-08-25,...,83,189.0,Mariano O'Kon,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766

In [22]:
procedures = procedures.merge(patients, left_on='PATIENT', right_on='Id')

In [23]:
procedures['START'] = pd.to_datetime(procedures['START'])
procedures['STOP'] = pd.to_datetime(procedures['STOP'])

procedures['BIRTHDATE'] = pd.to_datetime(procedures['BIRTHDATE'])
procedures['DEATHDATE'] = pd.to_datetime(procedures['DEATHDATE'])

procedures['AGE'] = procedures['START'].dt.year - procedures['BIRTHDATE'].dt.year

procedures['DURATION_IN_MINS'] = (procedures['STOP'] - procedures['START']).dt.total_seconds() / 60

procedures['FIRST'] = procedures['FIRST'].apply(lambda value: ''.join([i for i in value if not i.isdigit()]))
procedures['LAST'] = procedures['LAST'].apply(lambda value: ''.join([i for i in value if not i.isdigit()]))


procedures['PATIENT_NAME'] = procedures['FIRST'] + ' ' + procedures['LAST']

In [24]:
procedures.columns

Index(['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION',
       'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Id', 'BIRTHDATE',
       'DEATHDATE', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL',
       'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE',
       'COUNTY', 'ZIP', 'LAT', 'LON', 'AGE', 'DURATION_IN_MINS',
       'PATIENT_NAME'],
      dtype='object')

In [25]:
procedures = procedures[[
       'START', 'STOP',
       #'PATIENT', 'ENCOUNTER', 'CODE',
       'DESCRIPTION', 'BASE_COST',
     #  'REASONCODE',
       'REASONDESCRIPTION',
     #  'Id',
       'BIRTHDATE',
       'DEATHDATE',
      # 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN',  'MARITAL',
       'RACE',
       #'ETHNICITY',
       'GENDER', 'BIRTHPLACE',
     'ADDRESS',
       'CITY',
      'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON',
       'AGE', 'DURATION_IN_MINS', 'PATIENT_NAME'
]]

In [26]:
procedures = procedures.rename(columns={
    'REASONDESCRIPTION': 'REASON_DESCRIPTION'
})

In [27]:
procedures.head()

,START,STOP,DESCRIPTION,BASE_COST,REASON_DESCRIPTION,BIRTHDATE,DEATHDATE,RACE,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,AGE,DURATION_IN_MINS,PATIENT_NAME
0,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,Renal dialysis (procedure),903,NaN,1928-08-25,2017-02-04,white,M,Palermo Sicily IT,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766,83,212.0,Mariano O'Kon
1,2011-01-05 12:58:36+00:00,2011-01-05 16:42:36+00:00,Renal dialysis (procedure),1255,NaN,1928-08-25,2017-02-04,white,M,Palermo Sicily IT,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766,83,224.0,Mariano O'Kon
2,2011-01-08 16:42:36+00:00,2011-01-08 20:15:36+00:00,Renal dialysis (procedure),1556,NaN,1928-08-25,2017-02-04,white,M,Palermo Sicily IT,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766,83,213.0,Mariano O'Kon
3,2011-01-11 20:15:36+00:00,2011-01-11 22:49:36+00:00,Renal dialysis (procedure),828,NaN,1928-08-25,2017-02-04,white,M,Palermo Sicily IT,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766,83,154.0,Mariano O'Kon
4,2011-01-14 22:49:36+00:00,2011-01-15 01:58:36+00:00,Renal dialysis (procedure),1630,NaN,1928-08-25,2017-02-04,white,M,Palermo Sicily IT,531 Little Crossing,Boston,Massachusetts,Suffolk County,2132.0,42.358161,-71.037766,83,189.0,Mariano O'Kon

In [28]:
procedures.query('DURATION_IN_MINS < 1')

,START,STOP,DESCRIPTION,BASE_COST,REASON_DESCRIPTION,BIRTHDATE,DEATHDATE,RACE,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,AGE,DURATION_IN_MINS,PATIENT_NAME
6985,2017-05-01 02:13:23+00:00,2017-05-01 02:13:23+00:00,Combined chemotherapy and radiation therapy (p...,11121,Non-small cell carcinoma of lung TNM stage 1 ...,1960-09-13,2018-03-06,white,M,Boston Massachusetts US,283 Pacocha Mews Apt 98,Boston,Massachusetts,Suffolk County,2115.0,42.352635,-71.064639,57,0.0,Maurice Hermiston
45597,2017-04-02 17:59:33+00:00,2017-04-02 17:59:33+00:00,Combined chemotherapy and radiation therapy (p...,11619,Non-small cell carcinoma of lung TNM stage 1 ...,1954-03-27,2019-08-22,white,F,New Salem Massachusetts US,140 Huels Flat,Boston,Massachusetts,Suffolk County,2109.0,42.375837,-70.939501,63,0.0,Alexandria Heaney

In [29]:
procedures['START'] = pd.to_datetime(procedures['START']).dt.tz_localize(None)
encounters['START'] = pd.to_datetime(encounters['START']).dt.tz_localize(None)
procedures['STOP'] = pd.to_datetime(procedures['STOP']).dt.tz_localize(None)
encounters['STOP'] = pd.to_datetime(encounters['STOP']).dt.tz_localize(None)

In [ ]:
encounters.groupby('PAYER_COVERAGE')['PAYER_NAME'].count()

PAYER_COVERAGE
0.00         13586
0.31             1
0.34             1
3.05             1
4.16             2
             ...
79953.92         1
117114.30        1
159676.81        1
188453.17        1
247751.42        1
Name: PAYER_NAME, Length: 5606, dtype: int64

In [ ]:
encounters.groupby('PAYER_NAME')['PAYER_COVERAGE'].sum()

PAYER_NAME
Aetna                         1780.16
Anthem                           0.00
Blue Cross Blue Shield     2074496.34
Cigna Health                   968.35
Dual Eligible              1380705.87
Humana                        1953.86
Medicaid                   8417973.72
Medicare                  19215691.37
NO_INSURANCE                     0.00
UnitedHealthcare              3937.32
Name: PAYER_COVERAGE, dtype: float64

In [30]:
procedures.to_excel('procedures.xlsx', index=False)
encounters.to_excel('encounters.xlsx', index=False)